Better install
pesde-pkg/pesde pull request #17
Opened 2024-12-26 19:56 UTC by lukadev-0

Improves the install experience and refactors parts of the download and installation code.

The video below demonstrates the new experience. Downloads are artificially slowed down.

https://github.com/user-attachments/assets/5b56643c-c33b-40a5-b7b1-fac67e8e6315

2024-12-26 21:03 UTC, daimond113 requested changes
Thanks for the PR! I noticed a few details I'd like addressed, though.

2024-12-26 21:03 UTC, daimond113 commented on src/cli/install.rs
> +                    match fs::symlink_file(
Just want to confirm: does this work properly? Last I tried it threw a bunch of errors.

2024-12-26 21:03 UTC, daimond113 commented on src/cli/install.rs
> +                    exec lune run "$(dirname "$0")/.impl/{alias}.luau" -- "$@""#
Won't there be a bunch of whitespace in the written file due to this?

2024-12-26 21:03 UTC, daimond113 commented on src/cli/reporters.rs
> +    ProgressStyle::with_template("{prefix:.dim}{msg:>8.green} {spinner} [{elapsed_precise}]")
Would be cool if we could use orange like the progress bars before your PR for the message. Might be too light, though.

2024-12-26 21:10 UTC, lukadev-0 commented on src/cli/install.rs
> +                    exec lune run "$(dirname "$0")/.impl/{alias}.luau" -- "$@""#
Fixed.

2024-12-27 15:31 UTC, lukadev-0 commented on src/cli/install.rs
> +                    match fs::symlink_file(
I did some basic testing and it works fine, though there may be some edge cases I haven't tested for. Might need some thorough testing in the future.

2024-12-27 15:31 UTC, lukadev-0 commented on src/cli/reporters.rs
> +    ProgressStyle::with_template("{prefix:.dim}{msg:>8.green} {spinner} [{elapsed_precise}]")
I don't think it looks good.

2024-12-27 15:47 UTC, lukadev-0 commented on src/cli/reporters.rs
> +    ProgressStyle::with_template("{prefix:.dim}{msg:>8.green} {spinner} [{elapsed_precise}]")
Oh, you meant the message. Sure I'll try.

2024-12-27 18:50 UTC, daimond113 requested changes
Thanks for the corrections! There's one small issue left, though.

2024-12-27 18:50 UTC, daimond113 commented on src/main.rs
> +        .pretty()
```suggestion

```

We set it to pretty in in `#[cfg(not(debug_assertions))]`

2024-12-27 21:04 UTC, daimond113 approved these changes
LGTM!

2024-12-27 21:04 UTC, merged